// Generated by forgedascent/tools/gen_assets.py. Gates tier-less mining tools behind
// Forged Ascent tiers: the listed ingredient becomes 'any ingot of tier N'.
ServerEvents.recipes(event => {
  event.replaceInput({ output: 'create:mechanical_drill' }, '#c:ingots/iron', '#forgedascent:tier_materials/4')
  event.replaceInput({ output: 'immersiveengineering:drillhead_iron' }, '#c:ingots/iron', '#forgedascent:tier_materials/4')
  event.replaceInput({ output: 'stevescarts:module_iron_drill' }, 'minecraft:iron_ingot', '#forgedascent:tier_materials/4')
  event.replaceInput({ output: 'buildinggadgets2:gadget_destruction' }, '#c:ingots/iron', '#forgedascent:tier_materials/5')
  event.replaceInput({ output: 'mekanism:atomic_disassembler' }, '#mekanism:alloys/infused', '#forgedascent:tier_materials/7')
  event.replaceInput({ output: 'industrialforegoing:laser_drill' }, '#c:gears/gold', '#forgedascent:tier_materials/8')
})
