package com.imainjager.forgedascent.client;

import com.imainjager.forgedascent.ForgedAscent;
import com.imainjager.forgedascent.cthulhu.CthulhuRegistries;
import com.imainjager.forgedascent.cthulhu.EyeOfCthulhu;
import com.imainjager.forgedascent.cthulhu.EyeServant;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;
import software.bernie.geckolib.cache.object.GeoBone;
import software.bernie.geckolib.constant.DataTickets;
import software.bernie.geckolib.animation.AnimationState;
import software.bernie.geckolib.model.GeoModel;
import software.bernie.geckolib.renderer.GeoEntityRenderer;
import software.bernie.geckolib.renderer.layer.AutoGlowingGeoLayer;

import java.util.List;

/** Renderers for the Eye of Cthulhu and its Servants (GeckoLib models generated by tools/mobforge). */
@EventBusSubscriber(modid = ForgedAscent.MOD_ID, value = Dist.CLIENT)
public final class CthulhuClient {
    private CthulhuClient() {}

    @SubscribeEvent
    public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
        event.registerEntityRenderer(CthulhuRegistries.EYE.get(), EyeRenderer::new);
        event.registerEntityRenderer(CthulhuRegistries.SERVANT.get(), ServantRenderer::new);
    }

    /** Parts that only exist in phase 2 (the maw, the tendrils and the long end of the optic nerve). */
    private static final List<String> PHASE_TWO_BONES = List.of("jaw_upper", "jaw_lower", "maw_fixed",
            "tendril_a_1", "tendril_b_1", "nerve_5");

    static final class EyeModel extends GeoModel<EyeOfCthulhu> {
        private static final ResourceLocation MODEL = ForgedAscent.id("geo/entity/eye_of_cthulhu.geo.json");
        private static final ResourceLocation ANIMATIONS = ForgedAscent.id("animations/entity/eye_of_cthulhu.animation.json");
        private static final ResourceLocation SKIN_1 = ForgedAscent.id("textures/entity/eye_of_cthulhu.png");
        private static final ResourceLocation SKIN_2 = ForgedAscent.id("textures/entity/eye_of_cthulhu_phase2.png");

        @Override
        public ResourceLocation getModelResource(EyeOfCthulhu eye) {
            return MODEL;
        }

        @Override
        public ResourceLocation getTextureResource(EyeOfCthulhu eye) {
            return eye.phase() == 1 ? SKIN_1 : SKIN_2;
        }

        @Override
        public ResourceLocation getAnimationResource(EyeOfCthulhu eye) {
            return ANIMATIONS;
        }

        @Override
        public void setCustomAnimations(EyeOfCthulhu eye, long instanceId, AnimationState<EyeOfCthulhu> state) {
            super.setCustomAnimations(eye, instanceId, state);
            boolean phaseOne = eye.phase() == 1;
            for (String name : PHASE_TWO_BONES) {
                GeoBone bone = getAnimationProcessor().getBone(name);
                if (bone != null) bone.setHidden(phaseOne);
            }
            // the whole body tips up and down to look at what it is hunting
            GeoBone look = getAnimationProcessor().getBone("look");
            var data = state.getData(DataTickets.ENTITY_MODEL_DATA);
            if (look != null && data != null) {
                look.setRotX(data.headPitch() * Mth.DEG_TO_RAD);
            }
        }
    }

    static final class EyeRenderer extends GeoEntityRenderer<EyeOfCthulhu> {
        EyeRenderer(EntityRendererProvider.Context context) {
            super(context, new EyeModel());
            this.shadowRadius = 1.0F;
            addRenderLayer(new AutoGlowingGeoLayer<>(this));   // iris and maw keep glowing in the dark
        }

        @Override
        protected float getDeathMaxRotation(EyeOfCthulhu eye) {
            return 0.0F;   // the death animation does the dying
        }
    }

    static final class ServantModel extends GeoModel<EyeServant> {
        private static final ResourceLocation MODEL = ForgedAscent.id("geo/entity/servant_of_cthulhu.geo.json");
        private static final ResourceLocation ANIMATIONS = ForgedAscent.id("animations/entity/servant_of_cthulhu.animation.json");
        private static final ResourceLocation SKIN_1 = ForgedAscent.id("textures/entity/servant_of_cthulhu.png");
        private static final ResourceLocation SKIN_2 = ForgedAscent.id("textures/entity/servant_of_cthulhu_angry.png");

        @Override
        public ResourceLocation getModelResource(EyeServant servant) {
            return MODEL;
        }

        @Override
        public ResourceLocation getTextureResource(EyeServant servant) {
            return servant.getEntityData().get(EyeServant.ANGRY) ? SKIN_2 : SKIN_1;
        }

        @Override
        public ResourceLocation getAnimationResource(EyeServant servant) {
            return ANIMATIONS;
        }
    }

    static final class ServantRenderer extends GeoEntityRenderer<EyeServant> {
        ServantRenderer(EntityRendererProvider.Context context) {
            super(context, new ServantModel());
            this.shadowRadius = 0.25F;
            addRenderLayer(new AutoGlowingGeoLayer<>(this));
        }

        @Override
        protected float getDeathMaxRotation(EyeServant servant) {
            return 0.0F;
        }
    }
}
