package com.imainjager.forgedascent.client;

import com.imainjager.forgedascent.ForgedAscent;
import com.imainjager.forgedascent.mobs.EliteMobs;
import net.minecraft.client.model.geom.ModelLayers;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.PiglinRenderer;
import net.minecraft.client.renderer.entity.SkeletonRenderer;
import net.minecraft.client.renderer.entity.SpiderRenderer;
import net.minecraft.client.renderer.entity.WitchRenderer;
import net.minecraft.client.renderer.entity.WitherSkeletonRenderer;
import net.minecraft.client.renderer.entity.ZombieRenderer;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.monster.AbstractSkeleton;
import net.minecraft.world.entity.monster.Spider;
import net.minecraft.world.entity.monster.Witch;
import net.minecraft.world.entity.monster.WitherSkeleton;
import net.minecraft.world.entity.monster.Zombie;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.EntityRenderersEvent;

/** Elite mobs use the vanilla renderers with a recolored texture (generated by tools/gen_assets.py). */
@EventBusSubscriber(modid = ForgedAscent.MOD_ID, value = Dist.CLIENT)
public final class ForgedAscentClient {
    private ForgedAscentClient() {}

    @SubscribeEvent
    @SuppressWarnings("unchecked")
    public static void registerRenderers(EntityRenderersEvent.RegisterRenderers event) {
        EliteMobs.all().forEach((base, byElite) -> byElite.forEach((elite, holder) -> {
            ResourceLocation tex = ForgedAscent.id("textures/entity/elite/" + elite.id() + "_" + base.id + ".png");
            EntityType<?> type = holder.get();
            switch (base) {
                case ZOMBIE -> event.registerEntityRenderer((EntityType<Zombie>) type, zombie(tex));
                case SKELETON -> event.registerEntityRenderer((EntityType<AbstractSkeleton>) type, skeleton(tex));
                case SPIDER -> event.registerEntityRenderer((EntityType<Spider>) type, spider(tex));
                case WITHER_SKELETON -> event.registerEntityRenderer((EntityType<WitherSkeleton>) type, witherSkeleton(tex));
                case PIGLIN -> event.registerEntityRenderer((EntityType<Mob>) type, piglin(tex));
                case WITCH -> event.registerEntityRenderer((EntityType<Witch>) type, witch(tex));
            }
        }));
    }

    private static EntityRendererProvider<Zombie> zombie(ResourceLocation tex) {
        return ctx -> new ZombieRenderer(ctx) {
            @Override
            public ResourceLocation getTextureLocation(Zombie entity) {
                return tex;
            }
        };
    }

    private static EntityRendererProvider<AbstractSkeleton> skeleton(ResourceLocation tex) {
        return ctx -> new SkeletonRenderer<>(ctx) {
            @Override
            public ResourceLocation getTextureLocation(AbstractSkeleton entity) {
                return tex;
            }
        };
    }

    private static EntityRendererProvider<Spider> spider(ResourceLocation tex) {
        return ctx -> new SpiderRenderer<>(ctx) {
            @Override
            public ResourceLocation getTextureLocation(Spider entity) {
                return tex;
            }
        };
    }

    private static EntityRendererProvider<WitherSkeleton> witherSkeleton(ResourceLocation tex) {
        return ctx -> new WitherSkeletonRenderer(ctx) {
            @Override
            public ResourceLocation getTextureLocation(WitherSkeleton entity) {
                return tex;
            }
        };
    }

    private static EntityRendererProvider<Mob> piglin(ResourceLocation tex) {
        return ctx -> new PiglinRenderer(ctx, ModelLayers.PIGLIN, ModelLayers.PIGLIN_INNER_ARMOR,
                ModelLayers.PIGLIN_OUTER_ARMOR, false) {
            @Override
            public ResourceLocation getTextureLocation(Mob entity) {
                return tex;
            }
        };
    }

    private static EntityRendererProvider<Witch> witch(ResourceLocation tex) {
        return ctx -> new WitchRenderer(ctx) {
            @Override
            public ResourceLocation getTextureLocation(Witch entity) {
                return tex;
            }
        };
    }
}
